# Generated by Django 4.1.7 on 2023-04-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='lacality',
            new_name='address',
        ),
    ]
